# Generated by Django 4.2.7 on 2023-12-13 10:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='avgPoint',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
