# Generated by Django 4.2.7 on 2023-12-17 08:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_osmnxgraph_delete_click_delete_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('network_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='OSMnxGraph',
        ),
    ]
