# Generated by Django 4.2.7 on 2023-12-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
